# Project Information
site_name: zkSNARK wiki
site_description: A wiki for zkSNARKs
site_author: louhc
site_url: https://zksnark-wiki.github.io
strict: true

# Repository
repo_name: 'zksnark-wiki/zksnark-wiki.github.io'
repo_url: 'https://github.com/zksnark-wiki/zksnark-wiki.github.io'
edit_uri: 'blob/main/docs/'

# Copyright
copyright: 'none'

# Contents
nav:
  - zkSNARK-wiki:
    - zkSNARK-wiki: index.md
    - About: about.md
    - Contributing: contri.md
  - Primitives:
    - Primitives: primitives/index.md
  - Commitment:
    - Commitment: commitment/index.md
    - Pedersen Commitment: commitment/pedersen.md
  - PCS:
    - PCS: pcs/index.md
    - KZG Commitment: pcs/kzg.md
    - IPA Commitment: pcs/ipa.md
  - SNARK:
    - SNARK: snark/index.md
    - Libra: snark/libra.md
    - Virgo: snark/virgo.md
    - Virgo++: snark/virgo++.md
    # - Groth16: snark/groth16.md
    # - PLONK: snark/plonk.md
    # - Sonic: snark/sonic.md
    # - Marlin: snark/marlin.md
    # - Halo2: snark/halo2.md
  - Distributed ZKP:
    - Distributed ZKP: distributed/index.md
    - DeVirgo: distributed/devirgo.md
    - DIZK: distributed/dizk.md
    - Pianist: distributed/pianist.md
    - FRIttata: distributed/frittata.md
  - Space-Efficient ZKP:
    - Space-Efficient ZKP: space-efficient/index.md
    - Gemini: space-efficient/gemini.md
    - Sparrow: space-efficient/sparrow.md
    - Hobbit: space-efficient/hobbit.md
  
# Theme
theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'white'
    accent: 'pink'
  include_search_page: false
  search_index_only: true
  favicon: 'favicon.ico'

  # logo:
  #   icon: 'louhc'
  features:
    - navigation.tabs

  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

# Extensions

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  # - document-offsets-injection:
      # debug: true
  - admonition
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: ""
      # slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
